---
- name: Install JBoss EAP on RHEL and enable systemd unit
  hosts: managed
  become: yes
  vars:
    wildfly_install_workdir: /opt/jboss/
    wildfly_user: jboss
    wildfly_jvm_memory_min: 256m
    wildfly_jvm_memory_max: 512m
    wildfly_jvm_metaspace_size: 128m
    wildfly_java_package_name: java-11-openjdk-headless
    wildfly_home: /opt/jboss/jboss-eap-7.4
    wildfly_java_home: 
    wildfly_http_port: 8080
  vars_files:
    - rhn_credentials.yml
  roles:
    - redhat.jboss_eap.wildfly_install
    - redhat.jboss_eap.wildfly_systemd
    - redhat.jboss_eap.wildfly_validation
  tasks:
    - name: open firewall for jboss console
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      loop:
        - "8080/tcp"
        - "8443/tcp"

